plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\inetpub\\vs_code\\task5\\client\\frontend\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\inetpub\\vs_code\\task5\\client\\frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]